enum YosemiteEntryPointId {
	ALDER_CREEK = '621',
	ASPEN_VALLEY = '751',
	NELSON_LAKE = '881',
	HAPPY_ISLES_LITTLE_YOSEMITE_VALLEY = '702',
	HAPPY_ISLES_PAST_LITTLE_YOSEMITE_VALLEY = '703',
}

export default YosemiteEntryPointId;
